/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyPlansRouteImport } from './routes/weekly-plans'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecipeIdeasRouteImport } from './routes/recipe-ideas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GroceryListsRouteImport } from './routes/grocery-lists'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHelpRouteImport } from './routes/api/help'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WeeklyPlansRoute = WeeklyPlansRouteImport.update({
  id: '/weekly-plans',
  path: '/weekly-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdeasRoute = RecipeIdeasRouteImport.update({
  id: '/recipe-ideas',
  path: '/recipe-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListsRoute = GroceryListsRouteImport.update({
  id: '/grocery-lists',
  path: '/grocery-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpRoute = ApiHelpRouteImport.update({
  id: '/api/help',
  path: '/api/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery-lists': typeof GroceryListsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/help': typeof ApiHelpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery-lists': typeof GroceryListsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/help': typeof ApiHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery-lists': typeof GroceryListsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/help': typeof ApiHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/grocery-lists'
    | '/how-it-works'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
    | '/api/help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/grocery-lists'
    | '/how-it-works'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
    | '/api/help'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/grocery-lists'
    | '/how-it-works'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
    | '/api/help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GroceryListsRoute: typeof GroceryListsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RecipeIdeasRoute: typeof RecipeIdeasRoute
  RecipesRoute: typeof RecipesRoute
  WeeklyPlansRoute: typeof WeeklyPlansRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHelpRoute: typeof ApiHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-plans': {
      id: '/weekly-plans'
      path: '/weekly-plans'
      fullPath: '/weekly-plans'
      preLoaderRoute: typeof WeeklyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-ideas': {
      id: '/recipe-ideas'
      path: '/recipe-ideas'
      fullPath: '/recipe-ideas'
      preLoaderRoute: typeof RecipeIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-lists': {
      id: '/grocery-lists'
      path: '/grocery-lists'
      fullPath: '/grocery-lists'
      preLoaderRoute: typeof GroceryListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/help': {
      id: '/api/help'
      path: '/api/help'
      fullPath: '/api/help'
      preLoaderRoute: typeof ApiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GroceryListsRoute: GroceryListsRoute,
  HowItWorksRoute: HowItWorksRoute,
  RecipeIdeasRoute: RecipeIdeasRoute,
  RecipesRoute: RecipesRoute,
  WeeklyPlansRoute: WeeklyPlansRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHelpRoute: ApiHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
