/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyPlansRouteImport } from './routes/weekly-plans'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecipeIdeasRouteImport } from './routes/recipe-ideas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WeeklyPlansRoute = WeeklyPlansRouteImport.update({
  id: '/weekly-plans',
  path: '/weekly-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdeasRoute = RecipeIdeasRouteImport.update({
  id: '/recipe-ideas',
  path: '/recipe-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/recipe-ideas': typeof RecipeIdeasRoute
  '/recipes': typeof RecipesRoute
  '/weekly-plans': typeof WeeklyPlansRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/recipe-ideas'
    | '/recipes'
    | '/weekly-plans'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  RecipeIdeasRoute: typeof RecipeIdeasRoute
  RecipesRoute: typeof RecipesRoute
  WeeklyPlansRoute: typeof WeeklyPlansRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-plans': {
      id: '/weekly-plans'
      path: '/weekly-plans'
      fullPath: '/weekly-plans'
      preLoaderRoute: typeof WeeklyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-ideas': {
      id: '/recipe-ideas'
      path: '/recipe-ideas'
      fullPath: '/recipe-ideas'
      preLoaderRoute: typeof RecipeIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  RecipeIdeasRoute: RecipeIdeasRoute,
  RecipesRoute: RecipesRoute,
  WeeklyPlansRoute: WeeklyPlansRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
